"""
Resistance Measurement Guide for Accurate Power Calculations
============================================================

For the piezoelectric energy harvesting system, accurate resistance
measurement is CRITICAL for correct power and energy calculations.
"""

print("=" * 70)
print("RESISTANCE MEASUREMENT GUIDE")
print("=" * 70)
print()

print("WHY RESISTANCE MATTERS:")
print("-" * 70)
print("Power is calculated using: P = V² / R")
print("Energy is calculated using: E = P × Δt")
print()
print("If R is wrong → P is wrong → E is wrong → Your measurements are useless!")
print()

print("=" * 70)
print("WHAT RESISTANCE TO MEASURE:")
print("=" * 70)
print()
print("You need TOTAL circuit resistance (R_total), which includes:")
print()
print("  1. R_piezo     = Piezo element internal resistance")
print("  2. R_load      = Your load device resistance")
print("  3. R_series    = Any series resistors (protection, current limiting)")
print("  4. R_wiring    = Wire and connection resistance (usually ~1-5Ω)")
print()
print("Formula: R_total = R_piezo + R_load + R_series + R_wiring")
print()

print("=" * 70)
print("METHOD 1: DIRECT MEASUREMENT (RECOMMENDED)")
print("=" * 70)
print()
print("Equipment needed:")
print("  • Digital multimeter")
print()
print("Steps:")
print("  1. DISCONNECT the circuit from power/Pico")
print("  2. Set multimeter to resistance (Ω) mode")
print("  3. Touch probes across the ENTIRE circuit:")
print("     - One probe on piezo positive terminal")
print("     - Other probe on piezo negative terminal")
print("     (with load connected as it will be in operation)")
print("  4. Read the value: This is your R_total!")
print()
print("Example reading:")
print("  Multimeter shows: 1155Ω")
print("  → Use LOAD_RESISTANCE = 1155.0 in voltage.py")
print()

print("=" * 70)
print("METHOD 2: CALCULATE FROM VOLTAGE AND CURRENT")
print("=" * 70)
print()
print("Equipment needed:")
print("  • Your voltage sensor (already installed)")
print("  • Ammeter or current sensor")
print()
print("Steps:")
print("  1. Connect circuit normally with load")
print("  2. Tap/press piezo to generate voltage")
print("  3. Measure voltage (V) - read from your sensor")
print("  4. Measure current (I) - use ammeter in SERIES")
print("  5. Calculate: R_total = V / I")
print()
print("Example:")
print("  V = 2.5V (from your sensor)")
print("  I = 0.00217A = 2.17mA (from ammeter)")
print("  R_total = 2.5 / 0.00217 = 1152Ω")
print("  → Use LOAD_RESISTANCE = 1152.0")
print()

print("=" * 70)
print("METHOD 3: SUM INDIVIDUAL RESISTANCES")
print("=" * 70)
print()
print("Measure each component separately:")
print()
print("Step 1: Measure piezo internal resistance")
print("  • Disconnect piezo from circuit")
print("  • Multimeter across piezo terminals")
print("  • Note: Piezo elements typically 50-500Ω")
print()
print("Step 2: Measure load resistance")
print("  • Disconnect load from circuit")
print("  • Multimeter across load terminals")
print("  • Common values: LED~100Ω, resistor=marked value")
print()
print("Step 3: Measure any series resistors")
print("  • Remove from circuit")
print("  • Multimeter across resistor")
print()
print("Step 4: Estimate wire resistance")
print("  • Short wires (<30cm): ~1-2Ω")
print("  • Medium wires (30-100cm): ~3-5Ω")
print("  • Long wires (>100cm): ~5-10Ω")
print()
print("Step 5: Add them all")
print("  R_total = R_piezo + R_load + R_series + R_wiring")
print()
print("Example calculation:")
print("  R_piezo = 150Ω")
print("  R_load = 1000Ω (1kΩ resistor)")
print("  R_series = 0Ω (none installed)")
print("  R_wiring ≈ 5Ω (short wires)")
print("  ─────────────────")
print("  R_total = 1155Ω")
print("  → Use LOAD_RESISTANCE = 1155.0")
print()

print("=" * 70)
print("COMMON PIEZO RESISTANCES:")
print("=" * 70)
print()
print("Typical piezo element internal resistances:")
print("  • Small disc (Ø20mm): 100-200Ω")
print("  • Medium disc (Ø27-35mm): 200-400Ω")
print("  • Large disc (Ø50mm+): 300-600Ω")
print("  • Buzzer elements: 50-150Ω")
print()
print("Note: Always measure YOUR specific piezo!")
print()

print("=" * 70)
print("AFTER MEASURING:")
print("=" * 70)
print()
print("1. Update firmware/voltage.py:")
print()
print("   # Change line 33:")
print("   LOAD_RESISTANCE = 1155.0  # Your measured R_total")
print()
print("2. Redeploy to Pico:")
print()
print("   mpremote connect COM11 cp firmware/voltage.py :main.py")
print("   mpremote connect COM11 reset")
print()
print("3. Verify in dashboard:")
print("   • Power values should now be accurate")
print("   • Energy accumulation will be correct")
print()

print("=" * 70)
print("QUICK VERIFICATION TEST:")
print("=" * 70)
print()
print("To check if your resistance is correct:")
print()
print("1. Tap piezo and note voltage reading (e.g., V = 2.0V)")
print("2. Calculate expected power: P = V² / R")
print("   Example: P = (2.0)² / 1155 = 0.00346W = 3.46mW")
print("3. Check dashboard - power should match!")
print()
print("If power seems too high/low:")
print("  → Re-measure resistance")
print("  → Check for loose connections")
print("  → Verify load is properly connected")
print()

print("=" * 70)
print("IMPORTANT NOTES:")
print("=" * 70)
print()
print("⚠️  Use TOTAL resistance, not just load resistance")
print("⚠️  Resistance changes slightly with temperature")
print("⚠️  Measure with load CONNECTED as it will be used")
print("⚠️  For LEDs, measure at operating voltage (use dummy resistor)")
print("⚠️  Round to 1 decimal place is sufficient (e.g., 1155.0)")
print()
print("✅  After updating, power/energy will be accurate!")
print("✅  Your competition data will be scientifically valid!")
print()

print("=" * 70)
print("EXAMPLE SCENARIOS:")
print("=" * 70)
print()
print("Scenario 1: Simple 1kΩ Resistor Load")
print("  R_piezo = 150Ω (measured)")
print("  R_load = 1000Ω (1kΩ resistor)")
print("  R_total = 150 + 1000 = 1150Ω")
print("  → LOAD_RESISTANCE = 1150.0")
print()
print("Scenario 2: LED with Series Resistor")
print("  R_piezo = 200Ω")
print("  R_led = 80Ω (at operating current)")
print("  R_series = 220Ω (current limiting)")
print("  R_total = 200 + 80 + 220 = 500Ω")
print("  → LOAD_RESISTANCE = 500.0")
print()
print("Scenario 3: Supercapacitor Charging")
print("  R_piezo = 180Ω")
print("  R_charge_path = 10Ω (ESR + wiring)")
print("  R_total = 180 + 10 = 190Ω")
print("  → LOAD_RESISTANCE = 190.0")
print()

print("=" * 70)
print("Now measure your circuit and update the firmware!")
print("=" * 70)
