"""
COMPETITION REQUIREMENT: HC-05 Bluetooth Connection to PC
Step-by-step guide to enable SPP service properly
"""

print("=" * 70)
print("HC-05 BLUETOOTH SPP CONNECTION - COMPETITION SETUP")
print("=" * 70)
print()

print("GOAL: Get HC-05 data displaying on PC dashboard via Bluetooth")
print("REQUIREMENT: Must use Bluetooth (no USB shortcuts)")
print()

print("=" * 70)
print("THE PROBLEM")
print("=" * 70)
print()
print("✓ HC-05 is paired with Windows")
print("✓ COM ports exist (COM3-14)")
print("✗ No active SPP (Serial Port Profile) connection")
print("✗ Opening COM ports times out or hangs")
print()
print("ROOT CAUSE: Windows doesn't auto-activate SPP for HC-05")
print()

print("=" * 70)
print("SOLUTION: FORCE SPP SERVICE ACTIVATION")
print("=" * 70)
print()

print("STEP 1: Access HC-05 Services in Device Manager")
print("-" * 70)
print()
print("1. Press Windows + X")
print("2. Select 'Device Manager'")
print("3. Expand 'Bluetooth' section")
print("4. Find 'HC-05' (should show as paired)")
print("5. Right-click on 'HC-05' → Properties")
print("6. Go to 'Services' tab")
print()
print("LOOK FOR:")
print("  □ Serial Port (SPP)")
print()
print("IF UNCHECKED:")
print("  → Check the box to enable SPP")
print("  → Click Apply")
print("  → Click OK")
print()

print("STEP 2: Check Bluetooth Adapter COM Port Settings")
print("-" * 70)
print()
print("1. In Device Manager, find your Bluetooth adapter:")
print("   'Intel(R) Wireless Bluetooth(R)'")
print("2. Right-click → Properties")
print("3. Look for 'COM Ports' tab")
print()
print("IF 'COM Ports' tab exists:")
print("  → Click 'Add'")
print("  → Select 'Outgoing' (for connecting TO devices)")
print("  → Note the COM port number assigned")
print("  → Click OK")
print()
print("IF NO 'COM Ports' tab:")
print("  → Your driver might not support manual COM port setup")
print("  → Continue to next step")
print()

print("STEP 3: Remove and Re-pair HC-05 with PIN")
print("-" * 70)
print()
print("1. Windows Settings → Bluetooth & devices")
print("2. Find 'HC-05' in device list")
print("3. Click three dots → Remove device")
print("4. Confirm removal")
print()
print("5. Power cycle HC-05:")
print("   → Unplug Pico power")
print("   → Wait 5 seconds")
print("   → Plug back in")
print("   → HC-05 LED should blink fast (discoverable)")
print()
print("6. In Windows Bluetooth, click 'Add device'")
print("7. Select 'Bluetooth'")
print("8. Find 'HC-05' and click it")
print("9. WHEN ASKED FOR PIN, ENTER: 1234")
print("10. Wait for 'Connected' message")
print()

print("STEP 4: Verify Connection Status")
print("-" * 70)
print()
print("Check HC-05 LED pattern:")
print("  × Fast blinking (twice per second) = NOT connected")
print("  ✓ Slow blinking (once every 2 seconds) = CONNECTED")
print()
print("The LED MUST show slow blinking for data to work!")
print()

print("=" * 70)
print("ALTERNATIVE: Use Windows 'Bluetooth & other devices' Settings")
print("=" * 70)
print()
print("1. Windows Settings → Bluetooth & devices")
print("2. Scroll down to 'Devices'")
print("3. Find HC-05")
print("4. Click on it (don't click the three dots)")
print("5. Look for 'Connect' button")
print("6. Click 'Connect'")
print("7. HC-05 LED should change to slow blink")
print()

print("=" * 70)
print("TESTING AFTER SETUP")
print("=" * 70)
print()
print("After following the steps above, test the connection:")
print()
print("1. Make sure:")
print("   ✓ Pico is powered on")
print("   ✓ HC-05 LED is SLOW blinking (connected)")
print("   ✓ HC-05 is NOT connected to phone")
print()
print("2. Run the test script:")
print("   python firmware/quick_hc05_find.py")
print()
print("3. If data is found:")
print("   → Note the COM port")
print("   → Use it in the dashboard")
print("   → Competition ready! ✓")
print()

print("=" * 70)
print("IF NOTHING WORKS: LAST RESORT")
print("=" * 70)
print()
print("Your laptop's Bluetooth might genuinely not support SPP.")
print("This is common with newer Windows 11 systems.")
print()
print("COMPETITION DAY SOLUTIONS:")
print()
print("Option A: Borrow a USB Bluetooth Adapter")
print("  → Plugable USB-BT4LE (~$20)")
print("  → Has proper Classic Bluetooth SPP support")
print("  → Plug and play")
print("  → Will definitely work")
print()
print("Option B: Use a Different Laptop")
print("  → Try a friend's laptop")
print("  → Older laptops (Windows 10) often have better SPP support")
print()
print("Option C: Competition Day PC")
print("  → Use the competition venue's PC")
print("  → Many lab/competition PCs have better Bluetooth")
print()
print("Option D: Demonstrate with Phone")
print("  → Show judges HC-05 works perfectly with phone")
print("  → Explain Windows SPP limitation (technical knowledge!)")
print("  → Show dashboard in demo mode")
print("  → You won't lose points - it's a Windows driver issue")
print()

print("=" * 70)
print("NEXT ACTION")
print("=" * 70)
print()
print("Start with STEP 3 (Remove and Re-pair with PIN).")
print("This has the highest success rate.")
print()
print("Make sure HC-05 LED shows SLOW BLINK after pairing!")
print()
print("=" * 70)
