"""
Install Proper Bluetooth Driver with SPP Support
Replace Intel driver with one that supports Classic Bluetooth SPP
"""

print("=" * 70)
print("BLUETOOTH DRIVER REPLACEMENT GUIDE")
print("=" * 70)
print()

print("GOAL: Install driver with full Classic Bluetooth SPP support")
print("CURRENT DRIVER: Intel(R) Wireless Bluetooth(R)")
print("PROBLEM: Limited SPP (Serial Port Profile) support")
print()

print("=" * 70)
print("STEP 1: Backup Current Driver")
print("=" * 70)
print()
print("Before making changes, let's backup the current driver:")
print()
print("1. Press Windows + X → Device Manager")
print("2. Expand 'Bluetooth' section")
print("3. Right-click 'Intel(R) Wireless Bluetooth(R)'")
print("4. Select 'Properties'")
print("5. Go to 'Driver' tab")
print("6. Note down:")
print("   - Driver Version")
print("   - Driver Date")
print("   - Driver Provider")
print()
print("Take a screenshot or write this down!")
print()

print("=" * 70)
print("STEP 2: Try Microsoft Generic Bluetooth Driver")
print("=" * 70)
print()
print("Windows has a built-in generic driver that often has better SPP:")
print()
print("1. Device Manager → Bluetooth")
print("2. Right-click 'Intel(R) Wireless Bluetooth(R)'")
print("3. Select 'Update driver'")
print("4. Click 'Browse my computer for drivers'")
print("5. Click 'Let me pick from a list of available drivers'")
print()
print("6. You'll see a list of compatible drivers:")
print("   Look for:")
print("   - 'Generic Bluetooth Adapter'")
print("   - 'Microsoft Bluetooth Enumerator'")
print("   - Any driver WITHOUT 'Intel' in the name")
print()
print("7. Select 'Generic Bluetooth Adapter' or 'Microsoft' option")
print("8. Click 'Next'")
print("9. Windows will warn you - click 'Yes' to continue")
print("10. Wait for installation to complete")
print()
print("11. IMPORTANT: Restart your computer")
print()

print("=" * 70)
print("STEP 3: Re-pair HC-05 After Restart")
print("=" * 70)
print()
print("After restarting with new driver:")
print()
print("1. Power cycle the Pico/HC-05:")
print("   - Unplug power")
print("   - Wait 10 seconds")
print("   - Plug back in")
print()
print("2. Windows Settings → Bluetooth & devices")
print("3. Click 'Add device' → 'Bluetooth'")
print("4. Find 'HC-05'")
print("5. Enter PIN: 1234")
print("6. Wait for 'Connected'")
print("7. Check HC-05 LED - should be SLOW blinking")
print()

print("=" * 70)
print("STEP 4: Test the Connection")
print("=" * 70)
print()
print("Run the test script:")
print("  python firmware/quick_hc05_find.py")
print()
print("If successful:")
print("  ✓ One of the COM ports will show HC-05 data")
print("  ✓ Use that port in dashboard")
print("  ✓ Problem solved!")
print()

print("=" * 70)
print("IF GENERIC DRIVER DOESN'T HELP:")
print("=" * 70)
print()

print("OPTION A: Download Latest Intel Bluetooth Driver")
print("-" * 70)
print()
print("Sometimes newer Intel drivers have better SPP:")
print()
print("1. Visit: https://www.intel.com/content/www/us/en/download-center")
print("2. Search: 'Wireless Bluetooth'")
print("3. Download latest driver for your Windows version")
print("4. Install it")
print("5. Restart")
print("6. Re-pair HC-05")
print()

print("OPTION B: Roll Back to Older Intel Driver")
print("-" * 70)
print()
print("Older drivers sometimes have better SPP support:")
print()
print("1. Device Manager → Intel Bluetooth")
print("2. Properties → Driver tab")
print("3. Click 'Roll Back Driver' (if available)")
print("4. Or click 'Uninstall Device'")
print("5. Check 'Delete driver software'")
print("6. Restart")
print("7. Windows will auto-install older driver")
print()

print("OPTION C: Install Broadcom/Qualcomm Driver (if compatible)")
print("-" * 70)
print()
print("Some universal Bluetooth drivers work across chipsets:")
print()
print("1. Download Bluetooth Driver Installer:")
print("   https://bluetooth-driver-installer.updatestar.com/")
print("2. Run the installer")
print("3. It will detect your Bluetooth hardware")
print("4. Install recommended driver")
print("5. Restart and re-pair HC-05")
print()

print("=" * 70)
print("TO REVERT IF SOMETHING GOES WRONG:")
print("=" * 70)
print()
print("If new driver makes things worse:")
print()
print("1. Device Manager → Bluetooth adapter")
print("2. Right-click → Update driver")
print("3. Browse my computer → Let me pick")
print("4. Select original 'Intel(R) Wireless Bluetooth(R)'")
print("5. Click Next → Install")
print("6. Restart")
print()
print("Everything will be back to normal!")
print()

print("=" * 70)
print("RECOMMENDED SEQUENCE:")
print("=" * 70)
print()
print("1. Try Microsoft Generic Bluetooth Driver first (safest)")
print("2. If that doesn't work, try latest Intel driver")
print("3. If still not working, the hardware simply lacks SPP")
print("4. In that case: Get USB Bluetooth adapter ($15-20)")
print()
print("USB Bluetooth adapter is honestly the FASTEST solution!")
print()

print("=" * 70)
print("READY TO START?")
print("=" * 70)
print()
print("Begin with STEP 2 (Microsoft Generic Driver).")
print()
print("This is the safest option and often fixes SPP issues.")
print()
print("After installing and restarting, run:")
print("  python firmware/quick_hc05_find.py")
print()
print("to test if HC-05 data is now coming through!")
print()
print("=" * 70)
