"""
PuTTY HC-05 Connection Test Guide
"""

print("=" * 70)
print("PUTTY HC-05 CONNECTION TEST")
print("=" * 70)
print()

print("PuTTY is already installed on your system!")
print()

print("STEP-BY-STEP INSTRUCTIONS:")
print("=" * 70)
print()

print("1. Open PuTTY")
print("   - Press Windows key, type 'PuTTY'")
print("   - Click on 'PuTTY' application")
print()

print("2. Configure Connection")
print("   - Connection type: Select 'Serial' (radio button)")
print("   - Serial line: Enter one of these ports:")
print("     * COM4")
print("     * COM6")
print("     * COM7")
print("     * COM10")
print("     * COM13")
print("     * COM14")
print("   - Speed: 9600")
print()

print("3. Open Connection")
print("   - Click 'Open' button")
print("   - A black terminal window will appear")
print()

print("4. Watch for Data")
print("   - You should see data like:")
print("     'V: 0.003V | P: 0.00mW | E_inst: 0.000mJ | E_total: 0.000mWh'")
print("   - Data appears every 0.5 seconds")
print()

print("5. If No Data Appears")
print("   - Close PuTTY")
print("   - Try the NEXT COM port in the list")
print("   - Repeat until data appears")
print()

print("=" * 70)
print("WHAT TO EXPECT:")
print("=" * 70)
print()

print("✅ SUCCESS looks like:")
print("   V: 0.003V | P: 0.00mW | E_inst: 0.000mJ | E_total: 0.000mWh")
print("   V: 0.005V | P: 0.00mW | E_inst: 0.000mJ | E_total: 0.000mWh")
print("   V: 0.002V | P: 0.00mW | E_inst: 0.000mJ | E_total: 0.000mWh")
print("   (Updates continuously)")
print()

print("❌ NOT WORKING looks like:")
print("   - Blank screen with no text")
print("   - Error message about port")
print("   - Random garbage characters")
print()

print("=" * 70)
print("AFTER YOU FIND THE WORKING PORT:")
print("=" * 70)
print()

print("Once you see HC-05 data in PuTTY:")
print()
print("1. Note which COM port is working")
print("2. Close PuTTY")
print("3. Open dashboard: http://127.0.0.1:8000")
print("4. Click 'Connect' or 'Settings'")
print("5. Select the same COM port")
print("6. Set baud rate: 9600")
print("7. Click 'Connect'")
print("8. Dashboard will now show real-time voltage data!")
print()

print("=" * 70)
print("TROUBLESHOOTING:")
print("=" * 70)
print()

print("If ALL ports show blank screen:")
print("  1. Make sure Pico is powered on (red LED lit)")
print("  2. Check HC-05 LED - should be blinking")
print("  3. Try unplugging and replugging Pico power")
print("  4. Wait 5 seconds for HC-05 to initialize")
print("  5. Try PuTTY again")
print()

print("If you get 'Unable to open connection' error:")
print("  - That port might be in use")
print("  - Try a different COM port from the list")
print()

print("=" * 70)
print()
print("Ready? Open PuTTY now and try connecting!")
print()
print("Start with COM4, then try others if it doesn't work.")
print("=" * 70)
